import React from "react";
import Image from "next/image";
import {
  ArrowRight,
  Scale,
  Hammer,
  ShieldCheck,
  GraduationCap,
  Landmark,
  Compass,
} from "lucide-react";
import { assets } from "@/assets/assets";
import Button from "@/components/ui/Button";
import Reveal from "@/components/ui/Reveal";
import PageHeader from "@/components/ui/PageHeader";
import { Section, SectionHeading } from "@/components/ui/Section";

export const metadata = {
  title: "Leadership",
  description:
    "The character behind the record: the principles, defining moments and public service of Rt. Hon. Chibuike Rotimi Amaechi.",
};

/* Each principle is anchored to something that actually happened. A claim
   without evidence underneath it is just an adjective. */
const principles = [
  {
    icon: Compass,
    name: "Vision",
    claim: "Plan for the country you intend to leave behind.",
    body: "The rail programme was not a single line. It was a national grid, sequenced over seven years, connecting ports to hinterland and hinterland to market.",
    evidence: "1,763+ KM of standard gauge rail delivered",
  },
  {
    icon: Scale,
    name: "Courage",
    claim: "Take the fight to the institutions when the cause is right.",
    body: "Substituted on the ballot after winning his party's primary in 2007, he pursued the case through every tier of court rather than accept the outcome.",
    evidence: "Supreme Court ruled in his favour, 26 October 2007",
  },
  {
    icon: Hammer,
    name: "Execution",
    claim: "Finish what others abandoned.",
    body: "The Warri to Itakpe line had sat unfinished for three decades across successive administrations. It was completed and commissioned.",
    evidence: "326KM Warri to Itakpe completed after 30 years",
  },
  {
    icon: ShieldCheck,
    name: "Integrity",
    claim: "Public money is accounted for in public.",
    body: "Revenue generated by the new rail services was applied to servicing the facilities that built them, rather than absorbed into general spending.",
    evidence: "₦460M+ in rail revenue applied to loan repayment",
  },
  {
    icon: GraduationCap,
    name: "Service",
    claim: "Build the people who will run the system.",
    body: "Infrastructure without operators is a monument. Engineers and cadets were trained deliberately, at home and abroad, to run what was built.",
    evidence: "150 scholarships to China; 550+ maritime cadets trained",
  },
  {
    icon: Landmark,
    name: "Building institutions",
    claim: "Strengthen the office, not the officeholder.",
    body: "As Speaker he defended the autonomy of the State Assembly as an institution, including against the executive he belonged to.",
    evidence: "Chairman, Conference of Speakers of State Assemblies",
  },
];

/* Documented moments only. No invented milestones. */
const moments = [
  {
    year: "1999",
    title: "Elected Speaker, Rivers State House of Assembly",
    body: "Chosen to lead the chamber at his first term, and returned to the role for a second.",
  },
  {
    year: "2007",
    title: "Supreme Court affirms his mandate",
    body: "After being substituted as his party's candidate, the Court ruled on 26 October that he was the rightful candidate, and he was sworn in as Governor of Rivers State.",
  },
  {
    year: "2011",
    title: "Returned as Governor of Rivers State",
    body: "Returned for a second term on a record of roads, bridges, power projects and urban renewal.",
  },
  {
    year: "2015",
    title: "Director General, presidential campaign",
    body: "Ran the national campaign that produced the first defeat of a sitting Nigerian president at the ballot box.",
  },
  {
    year: "2015",
    title: "Appointed Federal Minister of Transportation",
    body: "Took charge of rail, ports and maritime, and began the largest railway modernisation programme in the country's history.",
  },
  {
    year: "2019",
    title: "Nominated again and confirmed",
    body: "Returned to the transport portfolio; the Senate granted him a 'take a bow' in recognition of his record.",
  },
  {
    year: "2022",
    title: "Called to the Bar",
    body: "Completed his legal education and was admitted, a return to study undertaken while in national office.",
  },
];

const credentials = [
  { label: "Honour", value: "Commander of the Order of the Niger (CON)" },
  { label: "Chieftaincy", value: "Dan Amanar Daura, Katsina State" },
  { label: "Education", value: "University of Port Harcourt, English & Literary Studies" },
  { label: "Education", value: "Master of Law, King's College London" },
  { label: "Origin", value: "Ubima, Ikwerre LGA, Rivers State" },
  { label: "Party", value: "African Democratic Congress" },
];

export default function LeadershipPage() {
  return (
    <>
      <PageHeader
        breadcrumb="Leadership"
        kicker="The character behind the record"
        title="Leadership is what you do when it costs you something."
        lead="Titles are given. Judgement, nerve and the will to see a thing through are demonstrated. What follows is the evidence, not the adjectives."
        image={assets.Amaechi5}
      >
        <div className="flex flex-col sm:flex-row">
          <Button href="/governance" variant="inverse" size="lg">
            The full journey
            <ArrowRight
              size={17}
              strokeWidth={3}
              className="transition-transform duration-300 group-hover:translate-x-1"
            />
          </Button>
          <Button
            href="/planforchange"
            variant="inverseOutline"
            size="lg"
            className="sm:-ml-0.5"
          >
            The plan
          </Button>
        </div>
      </PageHeader>

      {/* ------------------------------------------------------- principles */}
      <Section wide className="bg-white">
        <SectionHeading
          index={1}
          eyebrow="Principles"
          title="Six commitments, each with something underneath it"
          lead="Every principle below is followed by the specific, checkable thing that demonstrates it."
        />

        <div className="mt-16 grid gap-px bg-ink-200 md:grid-cols-2 lg:grid-cols-3">
          {principles.map((item, index) => {
            const Icon = item.icon;
            return (
              <Reveal
                key={item.name}
                delay={index * 60}
                className="group flex flex-col bg-white p-7 transition-colors duration-500 hover:bg-ink-950 lg:p-9"
              >
                <div className="flex items-center justify-between">
                  <Icon
                    size={24}
                    strokeWidth={1.75}
                    className="text-brand-600 transition-colors duration-500 group-hover:text-ember-500"
                  />
                  <span className="font-display text-[0.625rem] font-extrabold tracking-[0.2em] text-ink-400 uppercase transition-colors duration-500 group-hover:text-white/40">
                    {String(index + 1).padStart(2, "0")}
                  </span>
                </div>

                <h3 className="mt-7 text-fluid-xl text-ink-950 transition-colors duration-500 group-hover:text-white">
                  {item.name}
                </h3>
                <p className="mt-3 text-[0.9375rem] leading-snug font-semibold text-brand-700 transition-colors duration-500 group-hover:text-ember-400">
                  {item.claim}
                </p>
                <p className="mt-4 flex-1 text-[0.9375rem] leading-relaxed text-ink-600 transition-colors duration-500 group-hover:text-white/65">
                  {item.body}
                </p>

                <p className="mt-6 border-t border-ink-200 pt-4 text-[0.75rem] font-bold text-ink-950 transition-colors duration-500 group-hover:border-white/20 group-hover:text-white">
                  {item.evidence}
                </p>
              </Reveal>
            );
          })}
        </div>
      </Section>

      {/* ---------------------------------------------------------- moments */}
      <Section wide className="bg-ink-950">
        <SectionHeading
          index={2}
          eyebrow="Defining moments"
          title="The decisions that made the record"
          tone="inverse"
        />

        <ol className="mt-14">
          {moments.map((moment, index) => (
            <Reveal
              as="li"
              key={`${moment.year}-${moment.title}`}
              delay={index * 50}
              className="group grid gap-4 border-b border-white/15 py-8 transition-colors duration-500 hover:border-ember-500 lg:grid-cols-[8rem_1fr_1.1fr] lg:items-baseline lg:gap-10"
            >
              <span className="font-display text-fluid-2xl font-extrabold tracking-[-0.05em] text-ember-500 tabular-nums">
                {moment.year}
              </span>
              <h3 className="text-fluid-lg leading-snug text-white">
                {moment.title}
              </h3>
              <p className="leading-relaxed text-white/60">{moment.body}</p>
            </Reveal>
          ))}
        </ol>
      </Section>

      {/* ------------------------------------------------------ credentials */}
      <Section wide className="bg-white">
        <div className="grid gap-14 lg:grid-cols-[1fr_0.85fr] lg:gap-20">
          <div>
            <SectionHeading
              index={3}
              eyebrow="On the record"
              title="Background and honours"
            />

            <dl className="mt-12 border-t-2 border-ink-950">
              {credentials.map((item) => (
                <Reveal
                  key={item.value}
                  className="flex flex-col gap-1 border-b border-ink-200 py-5 sm:flex-row sm:items-baseline sm:gap-8"
                >
                  <dt className="w-32 shrink-0 text-[0.625rem] font-bold tracking-[0.16em] text-ink-500 uppercase">
                    {item.label}
                  </dt>
                  <dd className="text-[1.0625rem] leading-snug font-semibold text-ink-950">
                    {item.value}
                  </dd>
                </Reveal>
              ))}
            </dl>
          </div>

          <Reveal delay={120}>
            <figure className="relative">
              <div className="relative aspect-4/5 w-full">
                <Image
                  src={assets.Amaechi7}
                  alt="Rt. Hon. Chibuike Rotimi Amaechi"
                  fill
                  sizes="(max-width: 1024px) 100vw, 42vw"
                  className="object-cover object-top"
                />
              </div>
              <figcaption className="bg-ink-950 p-6 text-white">
                <p className="text-fluid-lg leading-snug font-semibold">
                  &ldquo;Governance must be measured by what it delivers, not by
                  what it promises.&rdquo;
                </p>
                <p className="mt-4 text-[0.6875rem] font-bold tracking-[0.16em] text-ember-400 uppercase">
                  Rt. Hon. Chibuike Rotimi Amaechi
                </p>
              </figcaption>
            </figure>
          </Reveal>
        </div>
      </Section>

      {/* -------------------------------------------------------------- CTA */}
      <section className="border-t-2 border-ink-950 bg-brand-600">
        <div className="shell shell-wide flex flex-col items-start justify-between gap-8 py-16 lg:flex-row lg:items-center lg:py-20">
          <div>
            <h2 className="text-fluid-3xl text-white">
              A record you can check. A plan you can read.
            </h2>
            <p className="mt-4 max-w-xl text-white/80">
              Decide for yourself, then decide whether to take part.
            </p>
          </div>
          <div className="flex shrink-0 flex-col sm:flex-row">
            <Button href="/planforchange" variant="inverse" size="lg">
              Read the plan
              <ArrowRight
                size={17}
                strokeWidth={3}
                className="transition-transform duration-300 group-hover:translate-x-1"
              />
            </Button>
            <Button
              href="/join"
              variant="inverseOutline"
              size="lg"
              className="sm:-ml-0.5"
            >
              Join the movement
            </Button>
          </div>
        </div>
      </section>
    </>
  );
}
